# Generated by Django 5.0.7 on 2024-07-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.EmailField(max_length=64),
        ),
    ]
