# Generated by Django 5.0.7 on 2024-07-19 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_password"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="users.usertype"
            ),
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
