# Generated by Django 5.0.7 on 2024-07-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_user_type_delete_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashier",
            name="Email",
            field=models.EmailField(
                default=1, max_length=255, unique=True, verbose_name="Email address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coach",
            name="Email",
            field=models.EmailField(
                default=1, max_length=255, unique=True, verbose_name="Email address"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="member",
            name="Email",
            field=models.EmailField(
                blank=True,
                max_length=255,
                null=True,
                unique=True,
                verbose_name="Email address",
            ),
        ),
    ]
