# Generated by Django 5.0.7 on 2024-07-22 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_cashier_email_coach_email_member_email"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cashier",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="coach",
            old_name="Email",
            new_name="email",
        ),
        migrations.RenameField(
            model_name="member",
            old_name="Email",
            new_name="email",
        ),
    ]
