# Generated by Django 5.0.7 on 2024-07-25 15:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_email_cashier_email_rename_email_coach_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashier',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cashier',
            name='edite_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='coach',
            name='edite_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='member',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='member',
            name='edite_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
