# Generated by Django 5.0.7 on 2024-07-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Billing', '0002_remove_invoice_date_remove_invoice_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='Archived',
            field=models.BooleanField(default=False),
        ),
    ]
